jobs:
  include:
    - stage: Tests
      language: node_js
      node_js: 12
      script:
      - pushd nodejs
      - npm test

    - stage: Deploy
      language: python
      python: 3.6
      env:
        - TF_INPUT=false
      install:
        - ./travis_install.sh
      script: 
        - python -c "print('Hi from Python!')"
        - ./travis_build.sh

