language: python
python:
  - "3.6"
env:
# Don't prompt for input!
  - TF_INPUT=false
install:
  - pip install -r requirements.txt
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.17/terraform_0.12.17_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mkdir -p ~/bin/
  - mv /tmp/terraform ~/bin/ 
  - export PATH="~/bin:$PATH"
script: 
  - pushd terraform
  - terraform init -input=false
  - terraform plan -out ./tfplan.tmp
  - terraform apply "./tfplan.tmp"